vich_uploader:
    db_driver: orm

    mappings:
        service_images:
            uri_prefix: /uploads/services
            upload_destination: '%kernel.project_dir%/public/uploads/services'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true