parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    twig.extension.intl:
        class: Twig\Extra\Intl\IntlExtension
        tags: ['twig.extension']

    # Configuration Doctrine manquante
    Doctrine\Common\Annotations\AnnotationReader:
        public: false
        arguments:
            - null

    doctrine.orm.metadata.annotation_reader:
        alias: Doctrine\Common\Annotations\AnnotationReader
        public: false

    doctrine.orm.default_annotation_metadata_driver:
        class: Doctrine\ORM\Mapping\Driver\AnnotationDriver
        arguments:
            - '@doctrine.orm.metadata.annotation_reader'
            - ['%kernel.project_dir%/src/Entity']
        tags:
            - { name: 'doctrine.orm.metadata_driver' }
    App\Service\FinancialReportService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $accountRepository: '@App\Repository\AccountRepository'
            $transactionRepository: '@App\Repository\TransactionRepository'
            $serviceRepository: '@App\Repository\ServiceRepository'